version: '3.7'

services:
  todo-frontend:
    image: node:15.14.0-slim
    container_name: todo-frontend
    command: sh -c "cd /home/node/todo-frontend && yarn start"
    volumes:
      - ./frontend:/home/node/todo-frontend

  todo-backend:
    image: node:15.14.0-slim
    container_name: todo-backend
    tty: true
    volumes:
      - ./backend:/home/node/todo-backend