version: '3.7'

services:
  todo-frontend:
    image: node:15.14.0-slim
    container_name: todo-frontend
    command: sh -c "su - node && cd /home/node/todo-frontend && yarn start"
    volumes:
      - ./frontend:/home/node/todo-frontend

  todo-backend:
    image: node:15.14.0-slim
    container_name: todo-backend
    command: sh -c "su - node && cd /home/node/todo-backend && npm run dev"
    volumes:
      - ./backend:/home/node/todo-backend
    depends_on:
      - todo-db
  todo-db:
    image: mysql:8.0.24
    container_name: todo-mysqld
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root